FROM ubuntu:latest

# Install depandencies and clean

RUN apt update -y && \
    apt upgrade -y && \
    apt install -y build-essential cmake bison flex libreadline-dev git && \
    git clone https://github.com/google/googletest.git && \
    mkdir googletest/build && cd googletest/build && \
    cmake .. && make && make install && \
    rm -rf /googletest
